/*
          # [Initial Schema Setup]
          This migration sets up the core tables for the Bookmark Manager application, including profiles, tags, bookmarks, and their relationships. It also establishes Row Level Security (RLS) to ensure users can only access their own data.

          ## Query Description: 
          This is a foundational migration and is safe to run on a new project. It creates new tables and does not modify existing data. It's designed to be the first step in setting up the application's database.

          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true (by dropping the created tables and functions)

          ## Structure Details:
          - Tables Created: `profiles`, `tags`, `bookmarks`, `bookmark_tags`
          - Functions Created: `handle_new_user`
          - Triggers Created: `on_auth_user_created`

          ## Security Implications:
          - RLS Status: Enabled on all new tables.
          - Policy Changes: Yes, new policies are created to restrict data access to the record owner.
          - Auth Requirements: Policies rely on `auth.uid()` to identify the current user.

          ## Performance Impact:
          - Indexes: Primary keys and foreign keys are indexed by default.
          - Triggers: A trigger is added to `auth.users` which fires once on user creation.
          - Estimated Impact: Low. The setup is standard and optimized for common query patterns.
        */

        -- 1. Profiles Table
        -- Stores public-facing user data.
        CREATE TABLE public.profiles (
            id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
            username text,
            avatar_url text,
            updated_at timestamptz,
            PRIMARY KEY (id),
            UNIQUE(username)
        );

        ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
        CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
        CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

        -- 2. Handle New User Trigger
        -- This trigger automatically creates a profile entry when a new user signs up.
        CREATE OR REPLACE FUNCTION public.handle_new_user()
        RETURNS trigger
        LANGUAGE plpgsql
        SECURITY DEFINER SET search_path = public
        AS $$
        BEGIN
          INSERT INTO public.profiles (id, username)
          VALUES (new.id, new.raw_user_meta_data->>'username');
          RETURN new;
        END;
        $$;

        CREATE TRIGGER on_auth_user_created
          AFTER INSERT ON auth.users
          FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

        -- 3. Tags Table
        -- Stores user-created tags for organizing bookmarks.
        CREATE TABLE public.tags (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at timestamptz NOT NULL DEFAULT now(),
            name text NOT NULL,
            user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE
        );

        ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Users can view their own tags." ON public.tags FOR SELECT USING (auth.uid() = user_id);
        CREATE POLICY "Users can insert their own tags." ON public.tags FOR INSERT WITH CHECK (auth.uid() = user_id);
        CREATE POLICY "Users can update their own tags." ON public.tags FOR UPDATE USING (auth.uid() = user_id);
        CREATE POLICY "Users can delete their own tags." ON public.tags FOR DELETE USING (auth.uid() = user_id);

        -- 4. Bookmarks Table
        -- Stores the core bookmark data.
        CREATE TABLE public.bookmarks (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at timestamptz NOT NULL DEFAULT now(),
            user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
            title text NOT NULL,
            description text,
            url text NOT NULL,
            favicon_url text,
            is_pinned boolean NOT NULL DEFAULT false,
            is_archived boolean NOT NULL DEFAULT false,
            view_count integer NOT NULL DEFAULT 0,
            last_visited_at timestamptz
        );

        ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Users can view their own bookmarks." ON public.bookmarks FOR SELECT USING (auth.uid() = user_id);
        CREATE POLICY "Users can insert their own bookmarks." ON public.bookmarks FOR INSERT WITH CHECK (auth.uid() = user_id);
        CREATE POLICY "Users can update their own bookmarks." ON public.bookmarks FOR UPDATE USING (auth.uid() = user_id);
        CREATE POLICY "Users can delete their own bookmarks." ON public.bookmarks FOR DELETE USING (auth.uid() = user_id);

        -- 5. Bookmark_Tags Junction Table
        -- Manages the many-to-many relationship between bookmarks and tags.
        CREATE TABLE public.bookmark_tags (
            bookmark_id bigint NOT NULL REFERENCES public.bookmarks ON DELETE CASCADE,
            tag_id bigint NOT NULL REFERENCES public.tags ON DELETE CASCADE,
            PRIMARY KEY (bookmark_id, tag_id)
        );

        ALTER TABLE public.bookmark_tags ENABLE ROW LEVEL SECURITY;
        -- Policies for this table are implicitly handled by the policies on the referenced tables.
        -- A user can only link/unlink tags and bookmarks that they own.
        CREATE POLICY "Users can manage links for their own bookmarks and tags." ON public.bookmark_tags
        FOR ALL
        USING (
          (SELECT user_id FROM public.bookmarks WHERE id = bookmark_id) = auth.uid() AND
          (SELECT user_id FROM public.tags WHERE id = tag_id) = auth.uid()
        )
        WITH CHECK (
          (SELECT user_id FROM public.bookmarks WHERE id = bookmark_id) = auth.uid() AND
          (SELECT user_id FROM public.tags WHERE id = tag_id) = auth.uid()
        );
